const formatJob = (job) => ({
  id: job.id,
  allowed_sc: job.meta.allowed_sc,
  featured_sc: job.meta.featured,
  company_name: job.meta.company_name,
  company_oib: job.meta.company_oib,
  title: job.meta.title,
  company: job.company,
  type: job.meta.type,
  job_type: job.meta.job_type,
  city: job.meta.city,
  work_start: job.meta.work_start,
  work_end: job.meta.work_end,
  payment_rate: job.meta.payment_rate,
  payment_other: job.meta.payment_other,
  work_hours: job.meta.work_hours,
  positions: job.meta.positions,
  active_until: job.meta.active_until,
  description: job.meta.description,
  whyme: job.meta.whyme,
  other_description: job.meta.other_description,
  skills: job.meta.skills,
  labels: job.meta.labels,
  contact_student: job.meta.contact_student,
  contact_sc: job.meta.contact_sc,
  documents: job.meta.documents,
  long_island_id: job.meta.long_island_id,
  categories: job.categories,
  date: job.date,
  updatedAt: job.modified,
  link: job.link,
});

export default formatJob;
